advanced_operations_of_kubernetes_with_kubeone:

kubermatic_kubernetes_platform_administration:

kubernetes_fundamentals_for_operators:
  # - event_id: codespaces
  #   trainees:
  #     - name: hubert-07

kubernetes_security:
  # - event_id: hackathon-01
  #   trainees:
  #     - name: hubert-01
  #     - name: daniel-01
  #     - name: burak

linux_fundamentals:
