apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "ks-syncagent:kdp-system:kubernetes-security-environment"
rules:
  - apiGroups:
      - kubernetes-security.training.cloud-native.com
    resources:
      - trainingprojects
      - trainingenvironments
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "ks-syncagent:kdp-system:kubernetes-security-environment"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "ks-syncagent:kdp-system:kubernetes-security-environment"
subjects:
  - kind: ServiceAccount
    name: "ks-syncagent"
    namespace: kdp-system
