apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: publish-kubernetes-security-project
  labels:
    training-name: ks-training
spec:
  naming:
    namespace: org-$remoteClusterName-$remoteNamespaceHash"
    name: "$remoteName"
  resource:
    kind: TrainingProject
    apiGroup: kubernetes-security.training.cloud-native.com
    version: v1alpha1
