apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtrainingenvironments.kubernetes-security.training.cloud-native.com
spec:
  group: kubernetes-security.training.cloud-native.com
  names:
    kind: XTrainingEnvironment
    plural: xtrainingenvironments
  claimNames:
    kind: TrainingEnvironment
    plural: trainingenvironments
  connectionSecretKeys:
    - service-account.json
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - parameters
              properties:
                parameters:
                  type: object
                  properties:
                    paused:
                      description: ""
                      type: boolean

